#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 6.0.{build}.0
install:
    - git clone https://github.com/johlju/DscResource.Tests
    - ps: Push-Location
    - ps: cd "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests"
    - git checkout add-certificate
    - ps: Pop-Location
    - ps: |
        $moduleName = 'xPSDesiredStateConfiguration'
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Default' `
            -CodeCoverage `
            -CodeCovIo `
            -DisableConsistency `
            -ExcludeTag @() `

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
  - ps: |
        Invoke-AppveyorAfterTestTask `
            -ResourceModuleName $moduleName
